// The fish shell layer, emitted verbatim by `ward shell init fish`
// (design/0025-fish-shell-layer/). It is hand-written fish — and it is
// allowed to be, because it holds no description of Ward's command tree:
// `wrr` forwards its arguments untouched, the workspace and repository
// functions ask `ward` where to go, and completion is either delegated to ward's own generated
// script (`complete -w`) or fed live by a callback. 0022's rule is against a
// SECOND description of the tree, not against a shell script.
//
// The fish itself now lives in `shorthands.ts`, as units
// (design/0027-shell-adoption/). This file is one ASSEMBLY of them — the
// always-fresh monolith the human redirects into `conf.d/` — and it owns only
// its own framing: the install header and the section banners that make a
// single 130-line file readable. `adopt.ts` is the other assembly, with its
// own framing and the same units, so the two can never define different fish.
import { FISH_HELPERS, FISH_SHORTHANDS, type ShellHelper, type Shorthand } from './shorthands.ts';

/**
 * The identifying header the emitted layer opens with. It is a constant
 * because doctor reads it: a `conf.d/ward.fish` that does not carry it was
 * not written by `ward shell init fish`, and doctor says so instead of
 * telling a human to overwrite their own file
 * (design/0026-shell-staleness-doctor/).
 */
export const FISH_LAYER_MARKER = '# ward — the fish shell layer.';

const HEADER = `${FISH_LAYER_MARKER} Generated by \`ward shell init fish\`; edits here
# are lost the next time you run it. Install it once:
#
#     ward shell init fish > ~/.config/fish/conf.d/ward.fish
#
# Every function below is plumbing: it gathers candidates by asking \`ward\`,
# optionally lets you pick one, and ends by invoking \`ward\` or \`cd\`. No
# knowledge of Ward's nouns, verbs, or records lives in this file.`;

/** A section banner, padded to the 78th column so the file reads as one document. */
function banner(title: string): string {
  return `# -- ${title} `.padEnd(78, '-');
}

const PICKER_SEAM_NOTE = `# The only two functions that know a picker exists, and the only place fzf is
# named. To swap in fzy, sk, or a future in-process \`ward\` picker, rewrite
# these two; nothing else in this file changes.`;

const COMPLETION_NOTE = `# wrr inherits ward's own generated completions by wrapping the command it
# forwards to, so the tree is never described twice (install them with
# \`ward completion fish\`). wrcd, wwcd, and wws are new names, so they carry
# their own — fed by the same callback the functions use, NAME<TAB>CUE being
# exactly what fish reads as a candidate and its description.`;

/** The picker seam, by name: the two helpers the note above is about. */
const SEAM = ['__ward_picker_present', '__ward_picker'];

function helper(name: string): ShellHelper {
  const found = FISH_HELPERS.find((candidate) => candidate.name === name);
  if (found === undefined) throw new Error(`no shell helper named '${name}'`);
  return found;
}

function bodies(units: readonly (ShellHelper | Shorthand)[]): string {
  return units.map((unit) => unit.body).join('\n\n');
}

/**
 * The whole layer, assembled: header, the picker seam, the resolver, the
 * shorthands, then every shorthand's completion in one block. The order is
 * the one 0025 wrote and the one the test asserts — the seam sits above every
 * shorthand, so it reads as a prologue rather than a habit.
 */
export const FISH_LAYER = [
  HEADER,
  `${banner('the picker seam')}\n${PICKER_SEAM_NOTE}`,
  bodies(SEAM.map(helper)),
  banner('candidate resolution'),
  bodies(FISH_HELPERS.filter((unit) => !SEAM.includes(unit.name))),
  banner('the shorthands'),
  bodies(FISH_SHORTHANDS),
  `${banner('completion')}\n${COMPLETION_NOTE}`,
  `${FISH_SHORTHANDS.map((shorthand) => shorthand.completion).join('\n')}\n`,
].join('\n\n');
