// The fish shell layer, emitted verbatim by `ward shell init fish`
// (design/0025-fish-shell-layer/). It is hand-written fish — and it is
// allowed to be, because it holds no description of Ward's command tree:
// `wrr` forwards its arguments untouched, the two `cd` functions ask `ward`
// where to go, and completion is either delegated to ward's own generated
// script (`complete -w`) or fed live by a callback. 0022's rule is against a
// SECOND description of the tree, not against a shell script.
//
// Kept as a string rather than a `.fish` file read at runtime so that what
// ships is what the module holds — no path resolution that differs between
// `bun src/cli/index.ts` and a compiled binary.

export const FISH_LAYER = `# ward — the fish shell layer. Generated by \`ward shell init fish\`; edits here
# are lost the next time you run it. Install it once:
#
#     ward shell init fish > ~/.config/fish/conf.d/ward.fish
#
# Every function below is plumbing: it gathers candidates by asking \`ward\`,
# optionally lets you pick one, and ends by invoking \`ward\` or \`cd\`. No
# knowledge of Ward's nouns, verbs, or records lives in this file.

# -- the picker seam ---------------------------------------------------------
# The only two functions that know a picker exists, and the only place fzf is
# named. To swap in fzy, sk, or a future in-process \`ward\` picker, rewrite
# these two; nothing else in this file changes.

function __ward_picker_present --description 'Whether an interactive picker is installed'
    command -q fzf
end

function __ward_picker --description 'Pick one NAME<TAB>CUE line from stdin; print its NAME'
    set -l prompt $argv[1]
    set -l query $argv[2]
    # --select-1 takes the choice when the prefilled query leaves exactly one
    # candidate standing, so a near-miss Ward could not resolve still costs no
    # keystroke. No --exit-0: a query that matches nothing should leave the
    # human in the picker, editing, not drop them back with silence.
    command fzf --prompt "$prompt> " --query "$query" --select-1 --no-multi \\
        --delimiter \\t --with-nth 1,2
end

# -- candidate resolution ----------------------------------------------------

function __ward_choose --description 'Resolve a candidate kind to one name, or say why not'
    set -l kind $argv[1]
    set -l prompt $argv[2]
    set -l query $argv[3]
    set -l candidates (command ward shell candidates $kind)
    if test (count $candidates) -eq 0
        echo "ward: nothing to pick from — ward knows no $kind from here" >&2
        return 1
    end
    if not __ward_picker_present
        # Degrade to a named lesser answer, never to a hang or a prompt: print
        # what could have been picked and let them name it.
        echo "ward: no picker installed — install fzf, or name one of these:" >&2
        printf '  %s\\n' (string replace -a \\t '  ' -- $candidates) >&2
        return 127
    end
    set -l chosen (printf '%s\\n' $candidates | __ward_picker $prompt $query)
    # Backing out of the picker is a choice, not a failure: say nothing.
    test -n "$chosen"; or return 130
    echo $chosen
end

# -- the shorthands ----------------------------------------------------------

function wrr --description 'ward repo refresh, from any directory'
    command ward repo refresh $argv
end

function wrcd --description 'cd to a repository checkout, from any directory'
    set -l name $argv[1]
    set -l target
    if test -n "$name"
        # Resolution is Ward's: exact, then a unique prefix, then a unique
        # substring, across the workspaces \`ward repo path\` searches. Its
        # stderr is deliberately not swallowed — an inexact match or a crossed
        # workspace is an implicit input, and reading why a name did not
        # resolve just before the picker opens is the point.
        set target (command ward repo path $name)
    end
    if test -z "$target"
        set name (__ward_choose repos repo "$name")
        or return $status
        set target (command ward repo path $name)
        or return $status
    end
    cd $target
end

function wwcd --description 'cd to a workspace root, from any directory'
    set -l name $argv[1]
    set -l target
    if test -n "$name"
        set target (command ward workspace path $name)
    else if not __ward_picker_present
        # Nothing named and nothing to pick with: a bare \`ward workspace path\`
        # means the default workspace, which is the answer worth having.
        echo "ward: no picker installed — going to the default workspace" >&2
        set target (command ward workspace path)
        or return $status
    end
    if test -z "$target"
        set name (__ward_choose workspaces workspace "$name")
        or return $status
        set target (command ward workspace path $name)
        or return $status
    end
    cd $target
end

# -- completion --------------------------------------------------------------
# wrr inherits ward's own generated completions by wrapping the command it
# forwards to, so the tree is never described twice (install them with
# \`ward completion fish\`). wrcd and wwcd are new names, so they carry their
# own — fed by the same callback the functions use, NAME<TAB>CUE being exactly
# what fish reads as a candidate and its description.

complete -c wrr -w 'ward repo refresh'
complete -c wrcd -f -a '(ward shell candidates repos)'
complete -c wwcd -f -a '(ward shell candidates workspaces)'
`;
